const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
function load(file,mocks={},cache=new Map()){
 file=path.resolve(file);if(cache.has(file))return cache.get(file).exports;
 const module={exports:{}};cache.set(file,module);
 const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText;
 function localRequire(name){if(name in mocks)return mocks[name];if(name.startsWith('@/'))return load(name.slice(2)+'.ts',mocks,cache);if(name.startsWith('.'))return load(path.resolve(path.dirname(file),name)+'.ts',mocks,cache);return require(name);}
 new Function('require','module','exports',code)(localRequire,module,module.exports);return module.exports;
}
const {appointmentSchema,lagosDate}=load('lib/appointment-validation.ts');
const valid={full_name:'Test Patient',phone:'+2348023445680',email:'',preferred_date:lagosDate(),preferred_time:'No preference',service:'dental',message:'',preferred_contact_method:'Phone'};
const key='12345678-1234-4123-8123-123456789012';
function request(body=valid,extra={}){return new Request('http://localhost/api/appointments',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key,...extra},body:typeof body==='string'?body:JSON.stringify(body)});}
test('server schema accepts verified service and Lagos date',()=>assert.equal(appointmentSchema.safeParse(valid).success,true));
test('rejects impossible dates, old dates and unsupported services',()=>{for(const change of [{preferred_date:'2027-02-30'},{preferred_date:'2000-01-01'},{service:'emergency'}])assert.equal(appointmentSchema.safeParse({...valid,...change}).success,false);});
test('email contact requires email, and oversized messages fail',()=>{for(const change of [{preferred_contact_method:'Email'},{email:'invalid'},{message:'x'.repeat(2001)},{website:'spam'},{status:'Confirmed'}])assert.equal(appointmentSchema.safeParse({...valid,...change}).success,false);});
function route(rpc){return load('app/api/appointments/route.ts',{'@supabase/supabase-js':{createClient:()=>({rpc})}}).POST;}
test('API rejects foreign origins, missing key and malformed JSON',async()=>{const post=route(()=>{throw Error('must not reach db');});assert.equal((await post(request(valid,{origin:'https://foreign.example'}))).status,403);assert.equal((await post(request(valid,{'Idempotency-Key':''}))).status,400);assert.equal((await post(request('{'))).status,400);});
test('API validates before touching database',async()=>{const post=route(()=>{throw Error('must not reach db');});const response=await post(request({...valid,service:'invented'}));assert.equal(response.status,422);assert.ok((await response.json()).fields.service);});
test('API bounds request body',async()=>{const post=route(()=>{throw Error('must not reach db');});assert.equal((await post(request(JSON.stringify({...valid,message:'x'.repeat(17000)})))).status,413);});
test('API fails closed when environment is absent',async()=>{const oldUrl=process.env.SUPABASE_URL,oldKey=process.env.SUPABASE_SERVICE_ROLE_KEY;delete process.env.SUPABASE_URL;delete process.env.SUPABASE_SERVICE_ROLE_KEY;try{assert.equal((await route(()=>{})(request())).status,503);}finally{if(oldUrl)process.env.SUPABASE_URL=oldUrl;if(oldKey)process.env.SUPABASE_SERVICE_ROLE_KEY=oldKey;}});
test('receipt comes only from successful RPC; secret and IP never returned',async()=>{process.env.SUPABASE_URL='https://test.invalid';process.env.SUPABASE_SERVICE_ROLE_KEY='unit-test-placeholder';try{let params;const post=route(async(name,p)=>{assert.equal(name,'submit_appointment');params=p;return {data:'NLPC-test-reference',error:null};});const response=await post(request(valid,{'x-nf-client-connection-ip':'192.0.2.1'}));assert.equal(response.status,201);assert.equal((await response.json()).reference_number,'NLPC-test-reference');assert.match(params.p_client_hash,/^[a-f0-9]{64}$/);assert.equal(params.p_request_key,key);assert.equal(response.headers.get('cache-control'),'no-store');}finally{delete process.env.SUPABASE_URL;delete process.env.SUPABASE_SERVICE_ROLE_KEY;}});
test('database, network, rate and conflicting retry errors are safe',async()=>{process.env.SUPABASE_URL='https://test.invalid';process.env.SUPABASE_SERVICE_ROLE_KEY='unit-test-placeholder';try{for(const [message,status] of [['secret database detail',503],['RATE_LIMIT',429],['IDEMPOTENCY_CONFLICT',409]]){const response=await route(async()=>({error:{message},data:null}))(request());assert.equal(response.status,status);assert.equal((await response.text()).includes('secret database detail'),false);}assert.equal((await route(async()=>{throw Error('connection failed');})(request())).status,503);}finally{delete process.env.SUPABASE_URL;delete process.env.SUPABASE_SERVICE_ROLE_KEY;}});

const {trustedClientAddress}=load('lib/request-client.ts');
test('Vercel identity uses its protected header and ignores spoofed alternatives',()=>{const h=new Headers({'x-vercel-forwarded-for':'192.0.2.4','x-forwarded-for':'198.51.100.9','x-nf-client-connection-ip':'198.51.100.8'});assert.equal(trustedClientAddress(h,{VERCEL:'1'}),'192.0.2.4');assert.equal(trustedClientAddress(h,{}),'unknown');});
test('platform identity validates IPs and handles Netlify and missing values',()=>{assert.equal(trustedClientAddress(new Headers({'x-vercel-forwarded-for':'not-an-ip'}),{VERCEL:'1'}),'unknown');assert.equal(trustedClientAddress(new Headers(),{VERCEL:'1'}),'unknown');assert.equal(trustedClientAddress(new Headers({'x-nf-client-connection-ip':'2001:db8::1'}),{NETLIFY:'true'}),'2001:db8::1');});
