import Link from 'next/link';
import { PageIntro } from '@/components/sections/page-intro';
import { EditorialSplit } from '@/components/sections/editorial-split';
import { CTABand } from '@/components/sections/cta-band';
import { CLINIC, SERVICES } from '@/lib/constants';
import { images } from '@/lib/images';
import { generateMetadata } from '@/lib/seo';
export const metadata=generateMetadata({title:'About NLPC',description:'New Life Poly Clinic Ltd is an outpatient clinic at 132 Iju Road, Fagba, Ifako-Ijaye, Lagos, offering seven healthcare services.',path:'/about'});
export default function About(){return <><PageIntro label="About" title="Local care. A considered place to begin." description={`${CLINIC.name} is an outpatient clinic at ${CLINIC.address.full}.`} /><section className="bg-accent py-16 lg:py-24"><div className="page-shell grid gap-10 lg:grid-cols-2"><div><p className="eyebrow">Our scope</p><h2 className="mt-5 font-display text-3xl sm:text-4xl">Seven services, one local setting.</h2><p className="body-copy mt-5">Our outpatient services cover medical consultancy, laboratory and diagnosis, audiological assessment, optometry, dental, pharmacy and dialysis.</p></div><ul className="divide-y divide-border">{SERVICES.map(s=><li key={s.slug}><Link href={`/services/${s.slug}`} className="flex min-h-[44px] justify-between gap-4 py-4 text-lg">{s.name}<span aria-hidden="true">↗</span></Link></li>)}</ul></div></section><EditorialSplit direction="text-right" eyebrow="Before you visit" title="Start with a conversation." body="Contact the clinic to discuss your needs and confirm arrangements. Our published opening hours are 8:00 AM – 5:00 PM. Ask about service availability before travelling." image={{...images.about.approach,alt:'Illustrative stock photograph of a medical conversation; not NLPC staff'}} ctas={[{label:'Patient information',href:'/patient-information'}]} /><p className="page-shell text-xs text-muted-foreground">Photography is illustrative and does not depict NLPC staff or facilities.</p><CTABand title="Find your next step." primaryCTA={{label:'Explore services',href:'/services'}} secondaryCTA={{label:'Contact the clinic',href:'/contact'}} /></>;}
