import { images } from './images';
export const SERVICE_CONTENT = {
'medical-consultancy': { image: images.services.medicalConsultancy.hero, layout: 'portrait', headline: 'A conversation about your health.', intro: 'Medical consultancy is available at NLPC for health concerns and check-ups.', focus: 'Make room for your questions', detail: 'Write down your concerns, when they began, and questions you want to ask. Bring relevant previous reports and a list of current medicines if available.', before: 'Contact the clinic about the consultation you need.' },
'medical-laboratory': { image: images.services.medicalLaboratory.hero, layout: 'landscape', headline: 'A clearer starting point for diagnosis.', intro: 'NLPC offers medical laboratory and diagnostic services. Ask about the specific test you need.', focus: 'Preparation starts with information', detail: 'Bring any test request or previous results you have. Ask whether your test is available, how to prepare, and how results will be provided. Preparation and timing vary by test.', before: 'Obtain preparation instructions directly from the clinic.' },
'audiological-assessment': { image: images.services.audiologicalAssessment.hero, layout: 'quiet', headline: 'Space to discuss your hearing.', intro: 'Audiological assessment is available among NLPC’s outpatient services.', focus: 'Describe what you have noticed', detail: 'Think about situations in which hearing feels different or difficult. Bring previous hearing reports if available. Ask the clinic to explain the assessment relevant to your visit.', before: 'Ask about arranging a hearing assessment and what to bring.' },
optometry: { image: images.services.optometry.hero, layout: 'landscape', headline: 'Bring your vision into focus.', intro: 'NLPC offers optometry services for eye care and vision assessment.', focus: 'Your everyday experience matters', detail: 'Note changes you have noticed in your vision. Bring current glasses or relevant eye reports if available. Ask about preparation and the assessment appropriate to your visit.', before: 'Contact the clinic about an eye or vision assessment.' },
dental: { image: images.services.dental.hero, layout: 'portrait', headline: 'A first step for oral health.', intro: 'Dental is one of NLPC’s seven outpatient services.', focus: 'Talk through your concern', detail: 'Bring relevant dental records if available, and note questions about your visit. Discuss specific procedures and availability directly with the clinic.', before: 'Explain your dental concern when contacting the clinic.' },
pharmacy: { image: images.services.pharmacy.hero, layout: 'quiet', headline: 'Practical support for your pharmacy visit.', intro: 'Pharmacy services and medication dispensing are available at NLPC.', focus: 'Bring the details you need', detail: 'Bring your prescription where applicable and a list of medicines you use. Ask about availability and medicines provided. This website does not provide individual medication advice.', before: 'Ask about your pharmacy enquiry and information to bring.' },
dialysis: { image: images.services.dialysis.hero, layout: 'quiet', headline: 'Plan your dialysis visit with the clinic.', intro: 'Dialysis is available among NLPC’s outpatient services. Confirm arrangements before travelling.', focus: 'Make arrangements before your visit', detail: 'Ask about availability, records needed, and arrangements relevant to your existing care plan. Bring referral information where applicable. An online request does not reserve a treatment session.', before: 'Speak directly with the clinic to discuss requirements and confirm arrangements.' },
} as const;
